import { cpSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { createServer } from 'node:http';
import { createRequire } from 'node:module';
import { join, relative } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import type { Project } from './project.js';

/** The preview app, compiled to JavaScript at build time from ../../preview (see its tsconfig). */
const TEMPLATE = fileURLToPath(new URL('../../templates/preview', import.meta.url));

/** A module specifier from `fromDir` to `target`, always relative and forward-slashed. */
function specifier(fromDir: string, target: string): string {
  const path = relative(fromDir, target).replace(/\\/g, '/');
  return path.startsWith('.') ? path : `./${path}`;
}

/**
 * Write the preview app into `<project>/.queek/preview`: a copy of the
 * template plus the files that point it at this project's theme. Regenerated
 * on every run, so a CLI update is picked up and hand edits never linger —
 * the `.next/` pattern. The folder ignores itself for git.
 */
export function writePreview(project: Project): string {
  const base = join(project.root, '.queek');
  const dir = join(base, 'preview');
  rmSync(dir, { recursive: true, force: true });
  mkdirSync(dir, { recursive: true });
  cpSync(TEMPLATE, dir, { recursive: true });
  writeFileSync(join(base, '.gitignore'), '# Generated by queek-theme. Safe to delete.\n*\n');

  const theme = specifier(dir, project.themeDir);
  const banner = '// Generated by queek-theme dev — regenerated on every run, do not edit.\n';
  // Plain JavaScript and no tsconfig.json: Next then has no TypeScript setup to
  // verify for the preview — it would try to install @types packages into the
  // developer's project otherwise — and still compiles the theme's .ts/.tsx.
  writeFileSync(join(dir, 'theme-entry.js'), `${banner}export { default } from '${theme}/index';\nexport { default as config } from '${theme}/theme.config';\nexport const THEME_DIR = ${JSON.stringify(project.themeDir)};\n`);
  writeFileSync(join(dir, 'theme-styles.js'), `${banner}import '${theme}/theme.css';\n`);
  writeFileSync(join(dir, 'next.config.mjs'), `${banner}/** @type {import('next').NextConfig} */
export default {
  // The kit ships TypeScript source so its 'use client' directives reach the bundler.
  transpilePackages: ['@usequeek/theme-kit'],
  images: { remotePatterns: [{ protocol: 'https', hostname: '**' }] },
  // Next's corner badge is not part of your theme; keep it out of the preview and its screenshots.
  devIndicators: false,
  // Your project is the root, so your theme folder — outside this one — resolves.
  turbopack: { root: ${JSON.stringify(project.root)} },
};
`);
  return dir;
}

type NextFactory = (options: { dev: boolean; dir: string; hostname: string; port: number; turbopack?: boolean }) => {
  prepare(): Promise<void>;
  getRequestHandler(): (req: unknown, res: unknown) => Promise<void>;
};

/**
 * Start Next's dev server on the preview — the official custom-server API
 * (https://nextjs.org/docs/app/guides/custom-server). Next comes from the
 * project's own install, so the preview renders with exactly the versions
 * the theme ships against.
 */
export async function startPreview(project: Project, dir: string, host: string, port: number): Promise<{ url: string; close: () => Promise<void> }> {
  const requireFromProject = createRequire(join(project.root, 'package.json'));
  let nextPath: string;
  try {
    nextPath = requireFromProject.resolve('next');
  } catch {
    throw new Error(`next is not installed in ${project.root}. Run \`npm install\` there first.`);
  }
  const imported = (await import(pathToFileURL(nextPath).href)) as { default: NextFactory | { default: NextFactory } };
  const next = (typeof imported.default === 'function' ? imported.default : imported.default.default) as NextFactory;

  const app = next({ dev: true, dir, hostname: host, port, turbopack: true });
  const handle = app.getRequestHandler();
  await app.prepare();

  const server = createServer((req, res) => void handle(req, res));
  await new Promise<void>((resolveListen, reject) => {
    server.once('error', reject);
    server.listen(port, host, () => resolveListen());
  });
  return {
    url: `http://${host === '0.0.0.0' ? 'localhost' : host}:${port}`,
    close: () => new Promise<void>((done) => server.close(() => done())),
  };
}
